import type {
  Beneficiary,
  BillRecord,
  BudgetRecord,
  CardControls,
  FDMaturityReminder,
  RecurringDepositRecord,
  RecurringPaymentItem,
  SavingsGoal,
  ScheduledPayment,
  ServiceRequest,
} from "@/types/banking";

export const initialServiceRequests: ServiceRequest[] = [
  {
    requestId: "SR-BKMT-2026-4019",
    requestType: "New cheque-book request",
    title: "Request for 50-leaf Personalized Cheque Book",
    description:
      "Requested personalized cheque book for Savings A/C 4092 1102 8842 dispatched to BKC communication address.",
    department: "Branch Operations",
    priority: "Medium",
    status: "In Progress",
    createdDate: "2026-09-28T10:30:00.000Z",
    lastUpdatedDate: "2026-09-29T14:15:00.000Z",
    slaDeadline: "2026-10-04T18:00:00.000Z",
    assignedTeam: "Dispatches & Clearing Operations",
    assignedEmployee: {
      name: "Ramesh Kulkarni",
      role: "Operations Officer",
      email: "ramesh.kulkarni@bankmate.io",
    },
    referenceNumber: "AWB-BLUEDART-8821049",
    internalNotes: "Cheque book printed. Dispatched via BlueDart AWB 8821049.",
    customerUpdates: [
      {
        timestamp: "2026-09-28T10:30:00.000Z",
        message:
          "Cheque book request registered successfully. Standard SLA: 4 working days.",
        author: "System Bot",
        isCustomerVisible: true,
      },
      {
        timestamp: "2026-09-29T14:15:00.000Z",
        message:
          "Your personalized cheque book has been printed and handed over to courier partner. Tracking ID: AWB-BLUEDART-8821049.",
        author: "Ramesh Kulkarni",
        isCustomerVisible: true,
      },
    ],
    isEscalated: false,
  },
  {
    requestId: "SR-BKMT-2026-3842",
    requestType: "Failed-transaction complaint",
    title: "UPI Debit without Merchant Settlement (₹4,850)",
    description:
      "Transaction to Swiggy Dineout failed at payment gateway on 25 Sep but amount was debited from Savings Account.",
    department: "Digital Payments & Chargeback",
    priority: "High",
    status: "Resolved",
    createdDate: "2026-09-25T21:10:00.000Z",
    lastUpdatedDate: "2026-09-26T11:40:00.000Z",
    slaDeadline: "2026-09-27T18:00:00.000Z",
    assignedTeam: "NPCI UPI Reconciliation Desk",
    assignedEmployee: {
      name: "Sneha Nair",
      role: "Chargeback Analyst",
      email: "sneha.nair@bankmate.io",
    },
    referenceNumber: "NPCI-REV-9021-X",
    internalNotes:
      "NPCI recon confirmed beneficiary bank timeout. Auto-reversal processed successfully.",
    customerUpdates: [
      {
        timestamp: "2026-09-25T21:10:00.000Z",
        message:
          "Complaint logged for ₹4,850 UPI transaction. Reconciliation initiated with NPCI.",
        author: "System Bot",
        isCustomerVisible: true,
      },
      {
        timestamp: "2026-09-26T11:40:00.000Z",
        message:
          "Resolution completed: Amount of ₹4,850 has been reversed to your Savings A/C (Ref: UPI-REV-902188).",
        author: "Sneha Nair",
        isCustomerVisible: true,
      },
    ],
    isEscalated: false,
  },
  {
    requestId: "SR-BKMT-2026-3205",
    requestType: "Re-KYC request",
    title: "Periodic Re-KYC Compliance Verification",
    description:
      "Scheduled video Re-KYC refresh for high net-worth premier tier status.",
    department: "Compliance & AML",
    priority: "Low",
    status: "Submitted",
    createdDate: "2026-09-20T16:00:00.000Z",
    lastUpdatedDate: "2026-09-20T16:00:00.000Z",
    slaDeadline: "2026-10-15T18:00:00.000Z",
    assignedTeam: "Centralized KYC Verification",
    assignedEmployee: {
      name: "Priya Sharma",
      role: "Senior Wealth Director & Dedicated RM",
      email: "priya.sharma@bankmate.io",
    },
    referenceNumber: "KYC-DOC-2026-4401",
    internalNotes:
      "Pre-verified via CKYC registry. Customer requested video Re-KYC slot for convenience.",
    customerUpdates: [
      {
        timestamp: "2026-09-20T16:00:00.000Z",
        message:
          "Re-KYC workflow created. RM Priya Sharma has been notified to schedule preferred video slot.",
        author: "Priya Sharma",
        isCustomerVisible: true,
      },
    ],
    isEscalated: false,
  },
];

export const initialBeneficiaries: Beneficiary[] = [
  {
    id: "ben_01",
    name: "Sunita Yadav",
    nickname: "Mom (Savings)",
    accountNumber: "5010 0341 9920",
    ifsc: "HDFC0000060",
    bankName: "HDFC Bank",
    accountType: "Savings",
    upiId: "sunita.yadav@okhdfcbank",
    dailyLimit: 200000,
    addedDate: "2024-02-10",
    status: "Active",
  },
  {
    id: "ben_02",
    name: "Rohit Verma",
    nickname: "Rohit (Colleague)",
    accountNumber: "0002 0158 3491",
    ifsc: "ICIC0000002",
    bankName: "ICICI Bank",
    accountType: "Savings",
    upiId: "rohit.verma@icici",
    dailyLimit: 100000,
    addedDate: "2025-05-18",
    status: "Active",
  },
  {
    id: "ben_03",
    name: "Apex Realty BKC Towers",
    nickname: "Apartment Maintenance",
    accountNumber: "9190 2004 8831",
    ifsc: "UTIB0000104",
    bankName: "Axis Bank",
    accountType: "Current",
    dailyLimit: 500000,
    addedDate: "2025-08-01",
    status: "Active",
  },
  {
    id: "ben_04",
    name: "Ananya Deshmukh",
    nickname: "Ananya Architect",
    accountNumber: "2044 1109 4321",
    ifsc: "SBIN0001821",
    bankName: "State Bank of India",
    accountType: "Savings",
    upiId: "ananya.d@oksbi",
    dailyLimit: 100000,
    addedDate: "2026-10-02",
    coolingPeriodEnds: "2026-10-03T18:00:00.000Z",
    status: "Cooling Period",
  },
];

export const initialScheduledPayments: ScheduledPayment[] = [
  {
    id: "sch_01",
    scheduledDate: "2026-10-05T09:00:00.000Z",
    frequency: "Monthly",
    recipientName: "Apex Realty BKC Towers",
    recipientAccount: "Axis A/C 9190 •••• 8831",
    amount: 32500,
    purpose: "Society Maintenance & Parking Dues",
    type: "NEFT",
    status: "Active",
    nextExecutionDate: "2026-10-05",
    sourceAccount: "Premier Privilege Savings (•••• 8842)",
  },
  {
    id: "sch_02",
    scheduledDate: "2026-10-10T10:00:00.000Z",
    frequency: "Monthly",
    recipientName: "Sunita Yadav",
    recipientAccount: "HDFC A/C 5010 •••• 9920",
    amount: 50000,
    purpose: "Monthly Family Care Support",
    type: "IMPS",
    status: "Active",
    nextExecutionDate: "2026-10-10",
    sourceAccount: "Corporate Salary A/C (•••• 1928)",
  },
];

export const initialBills: BillRecord[] = [
  {
    id: "bill_01",
    billerName: "Tata Power Mumbai",
    category: "Electricity",
    consumerNumber: "9000 1284 9210",
    billAmount: 6420,
    dueDate: "2026-10-08",
    status: "Unpaid",
    billPeriod: "Sep 2026",
  },
  {
    id: "bill_02",
    billerName: "Tata Play DTH & Broadband",
    category: "Broadband",
    consumerNumber: "1084 9281 90",
    billAmount: 1899,
    dueDate: "2026-10-12",
    status: "Unpaid",
    billPeriod: "Oct 2026",
  },
  {
    id: "bill_03",
    billerName: "Mahanagar Gas Limited (MGL)",
    category: "Gas",
    consumerNumber: "4001 0294 88",
    billAmount: 1140,
    dueDate: "2026-10-14",
    status: "Unpaid",
    billPeriod: "Bi-Monthly Sep-Oct",
  },
  {
    id: "bill_04",
    billerName: "BankMate Metal Reserve Visa Infinite",
    category: "Credit Card",
    consumerNumber: "4129 •••• •••• 9904",
    billAmount: 115800,
    dueDate: "2026-10-15",
    status: "Unpaid",
    billPeriod: "Cycle ending 20 Sep 2026",
  },
];

export const initialCardControls: Record<string, CardControls> = {
  card_credit_01: {
    cardId: "card_credit_01",
    cardNumberMasked: "4129 •••• •••• 9904",
    isBlockedTemporarily: false,
    isLostReported: false,
    contactlessEnabled: true,
    internationalEnabled: true,
    onlineEcommerceEnabled: true,
    atmDailyLimit: 100000,
    atmMaxLimit: 200000,
    posDailyLimit: 400000,
    posMaxLimit: 500000,
    pinLastChanged: "2026-06-12",
    rewardPoints: 34250,
    rewardValue: 8562.5,
    disputes: [],
  },
  card_debit_01: {
    cardId: "card_debit_01",
    cardNumberMasked: "5241 •••• •••• 7701",
    isBlockedTemporarily: false,
    isLostReported: false,
    contactlessEnabled: true,
    internationalEnabled: false,
    onlineEcommerceEnabled: true,
    atmDailyLimit: 100000,
    atmMaxLimit: 150000,
    posDailyLimit: 300000,
    posMaxLimit: 400000,
    pinLastChanged: "2026-04-10",
    rewardPoints: 4800,
    rewardValue: 1200.0,
    disputes: [],
  },
};

export const initialBudgets: BudgetRecord[] = [
  {
    id: "bud_01",
    category: "Dining & Food Delivery",
    monthlyBudget: 35000,
    currentSpend: 24850,
    period: "September 2026",
    color: "#F59E0B",
  },
  {
    id: "bud_02",
    category: "Groceries & Household",
    monthlyBudget: 30000,
    currentSpend: 18200,
    period: "September 2026",
    color: "#10B981",
  },
  {
    id: "bud_03",
    category: "Shopping & Retail",
    monthlyBudget: 40000,
    currentSpend: 36400,
    period: "September 2026",
    color: "#6366F1",
  },
  {
    id: "bud_04",
    category: "Travel & Fuel",
    monthlyBudget: 25000,
    currentSpend: 14600,
    period: "September 2026",
    color: "#3B82F6",
  },
  {
    id: "bud_05",
    category: "Entertainment & Subscriptions",
    monthlyBudget: 15000,
    currentSpend: 11250,
    period: "September 2026",
    color: "#EC4899",
  },
];

export const initialSavingsGoals: SavingsGoal[] = [
  {
    id: "goal_01",
    title: "Luxury Electric Vehicle Down Payment",
    targetAmount: 1500000,
    currentAmount: 1050000,
    targetDate: "2027-03-31",
    category: "Vehicle",
    color: "#10B981",
  },
  {
    id: "goal_02",
    title: "Switzerland Alpine Vacation 2027",
    targetAmount: 600000,
    currentAmount: 420000,
    targetDate: "2027-06-15",
    category: "Travel",
    color: "#3B82F6",
  },
  {
    id: "goal_03",
    title: "Emergency Contingency Fund (1 Year Living)",
    targetAmount: 1800000,
    currentAmount: 1500000,
    targetDate: "2026-12-31",
    category: "Emergency",
    color: "#8B5CF6",
  },
];

export const initialRecurringPayments: RecurringPaymentItem[] = [
  {
    id: "rec_01",
    merchant: "Netflix India 4K Premium",
    amount: 649,
    frequency: "Monthly",
    nextDueDate: "2026-10-18",
    category: "Entertainment",
    autoDebitEnabled: true,
  },
  {
    id: "rec_02",
    merchant: "Spotify Premium Duo",
    amount: 149,
    frequency: "Monthly",
    nextDueDate: "2026-10-11",
    category: "Entertainment",
    autoDebitEnabled: true,
  },
  {
    id: "rec_03",
    merchant: "Amazon Prime Annual Plan",
    amount: 1499,
    frequency: "Annual",
    nextDueDate: "2027-01-20",
    category: "Entertainment",
    autoDebitEnabled: true,
  },
  {
    id: "rec_04",
    merchant: "Cult.fit Elite Annual Membership",
    amount: 19500,
    frequency: "Annual",
    nextDueDate: "2026-11-04",
    category: "Utility",
    autoDebitEnabled: false,
  },
  {
    id: "rec_05",
    merchant: "Auto Loan EMI (LN-AUTO-4091)",
    amount: 19250,
    frequency: "Monthly",
    nextDueDate: "2026-10-05",
    category: "Loan EMI",
    autoDebitEnabled: true,
  },
];

export const initialFDReminders: FDMaturityReminder[] = [
  {
    id: "rem_01",
    fdNumber: "FD-994021-A",
    maturityDate: "2027-10-15",
    maturityAmount: 1264800,
    reminderDate: "2027-10-01",
    notificationChannel: "Email & SMS",
    status: "Active",
  },
  {
    id: "rem_02",
    fdNumber: "FD-883190-B",
    maturityDate: "2028-03-20",
    maturityAmount: 578500,
    reminderDate: "2028-03-05",
    notificationChannel: "WhatsApp",
    status: "Active",
  },
];

export const initialRecurringDeposits: RecurringDepositRecord[] = [
  {
    id: "rd_01",
    rdNumber: "RD-BKMT-2026-1049",
    monthlyDeposit: 25000,
    tenureMonths: 12,
    interestRate: 7.15,
    maturityAmount: 311850,
    startDate: "2026-05-01",
    maturityDate: "2027-05-01",
    status: "Active",
    nextDeductionDate: "2026-10-05",
  },
];
